# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TMD_IDW_Class
                                 A QGIS plugin
 Interpolation data from TMD
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-10-28
        copyright            : (C) 2019 by i-bitz
        email                : aaa@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TMD_IDW_Class class from file TMD_IDW_Class.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TMD_IDW import TMD_IDW_Class
    return TMD_IDW_Class(iface)
